apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: server
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: 692138114203.dkr.ecr.ap-northeast-1.amazonaws.com/first-app-server:latest