apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: server
spec:
  selector:
    app: server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080