apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: bff
  labels:
    app: bff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: 692138114203.dkr.ecr.ap-northeast-1.amazonaws.com/first-app-bff:latest
          env:
            - name: PORT
              value: "8080"
            - name: SERVER_SERVICE_URL
              value: "http://dev-server-service.dev-server:8080"
#              value: $(SERVER_SERVICE_URL)
          ports:
            - containerPort: 8080