apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bff
resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
vars:
  - name: SERVER_SERVICE_URL
    objref:
      kind: Deployment
      name: bff
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.labels.server_service_url
  - name: PORT
    objref:
      kind: Deployment
      name: bff
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.labels.port_num